### ISSUE TITLE
Error when generating dereplicated versions of the unique fasta file for a locus

### ISSUE THREAD

**Issue by juanboja** [GuilhemSempere/mbctools#15]
Hello, I have started to use the mbctools program and I have encountered a problem when I want to generate the dereplicated versions of the unique fasta file for a locus.

I am analyzing 3 loci, first the 12S, 16S and finally COI. When used the 3a option all the loci generated a unique sequence file. WHen I said yes to generate the dereplicated version of the files, the 12S locus worked correctly, but the COI and 16S both found an error that exited the program. The error is the following:
```
Locus 16S: 133 sequences from 36 samples were added to a unique fasta file
Results in --> /home/dna_server/Documentos/mbctools/eDNA_Guayas/results_by_locus/16S/16S_allseq_select.fasta

Do you want to generate dereplicated versions of the above mentioned fasta file? Enter yes or no: yes

Dereplicating sample sequences by locus for 16S...
Traceback (most recent call last):
  File "/usr/local/bin/mbctools", line 5, in <module>
    from mbctools.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/mbctools/__main__.py", line 6, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/mbctools/mbctools.py", line 2687, in main
    main_menu3()
  File "/usr/local/lib/python3.9/site-packages/mbctools/mbctools.py", line 1906, in main_menu3
    concat_3(lociPEs + list(set(lociSEs) - set(lociPEs)) if rmenu == '3a' else None)
  File "/usr/local/lib/python3.9/site-packages/mbctools/mbctools.py", line 1787, in concat_3
    derepResults = derepSeveralFastaFiles({loc2cat : loc2cat + '_allseq_select.fasta'}, loc2cat + '_allseq_select_derep.fasta', loc2cat + '_allseq_select_derep.tsv', logFile)
  File "/usr/local/lib/python3.9/site-packages/mbctools/mbctools.py", line 2242, in derepSeveralFastaFiles
    retVal = derepBasedOnIDs({", ".join(locusToFastaDict.keys()) : outFastaName + ".tmp2"}, outFastaName, outTsvName)
  File "/usr/local/lib/python3.9/site-packages/mbctools/mbctools.py", line 2205, in derepBasedOnIDs
    seqOrientations[splitIdLine[0]] = re.search(readTypePattern, splitIdLine[1]).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
(vsearch) [root@localhost eDNA_Guayas]#
```

I hope this is helpful. If more info is needed just let me know.

JB

**Comment by GuilhemSempere** [comment]
Hi
Could you provide the contents of 16S_allseq_select.fasta, 12S_allseq_select.fasta and COI_allseq_select.fasta. If data is confidential you can remove or randomize the actual sequence strings, I'm only interested in the sequence IDs

**Comment by juanboja** [comment]
Hi [Guilhem](https://github.com/GuilhemSempere),

Here are the IDs of all the files.

[Locus.allseq.files.zip](https://github.com/GuilhemSempere/mbctools/files/14389377/Locus.allseq.files.zip)

**Comment by GuilhemSempere** [comment]
Are you sure to be using the latest version os mbctools? This looks much like a bug fixed in december. How did you install the software?

**Comment by juanboja** [comment]
I installed it via pip

`pip3.9 install mbctools`

I have version 1.0a2

```
(vsearch) [root@localhost ~]# pip3.9 install mbctools
Requirement already satisfied: mbctools in /usr/local/lib/python3.9/site-packages (1.0a2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by GuilhemSempere** [comment]
Please type pip show mbctools then go to the specified location then into mbctools folder and send me mbctools.py

**Comment by juanboja** [comment]
Here it is

[mbctools.zip](https://github.com/GuilhemSempere/mbctools/files/14407599/mbctools.zip)

**Comment by GuilhemSempere** [comment]
Well it looks good. Can you send me lociSE.txt, lociPE.txt, samples.txt ?

**Comment by juanboja** [comment]
Sure.

[samples.txt](https://github.com/GuilhemSempere/mbctools/files/14407796/samples.txt)
[lociPE.txt](https://github.com/GuilhemSempere/mbctools/files/14407797/lociPE.txt)
[lociSE.txt](https://github.com/GuilhemSempere/mbctools/files/14407798/lociSE.txt)

**Comment by GuilhemSempere** [comment]
Did you use option 2b or 2d? Can you try and use the one you didn't use and see if 3a then works?

**Comment by juanboja** [comment]
I used option 2a. I'll try the other options and get back to you.

**Comment by GuilhemSempere** [comment]
I think I found the problem. Can you please replace your mbctools.py with this one and retry as usual? NB: I think you used 2a AND 2b (or 2d) otherwise there would be no single-end reads accounted for (and that's where the problem lies)
[mbctools.zip](https://github.com/GuilhemSempere/mbctools/files/14417913/mbctools.zip)

**Comment by juanboja** [comment]
You are right, I just finished running everything again and used option 2a and then 3a, and everything worked well. I will go ahead and the new mbctools.py file and let you know if this fixes the previous problem.

UPDATE: I have tried the 2a and 2b/2d followed by 3a/3b and it worked. thanks. I am closing the thread.
